//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\My Dev\mlo\Mlo.Examples.Antlr4\Mlo.Examples.Antlr4.SqlParserExample01\SqlParser.g4 by ANTLR 4.5.3

// Unreachable code detected

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;

#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Mlo.Examples.Antlr4.DemoApp02.Parsers {

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SqlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public interface ISqlParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.sql"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSql([NotNull] SqlParser.SqlContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] SqlParser.StatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.data_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_statement([NotNull] SqlParser.Data_statementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.data_change_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_change_statement([NotNull] SqlParser.Data_change_statementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.schema_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSchema_statement([NotNull] SqlParser.Schema_statementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.index_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_statement([NotNull] SqlParser.Index_statementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.create_table_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_table_statement([NotNull] SqlParser.Create_table_statementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.table_elements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_elements([NotNull] SqlParser.Table_elementsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.field_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField_element([NotNull] SqlParser.Field_elementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.field_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField_type([NotNull] SqlParser.Field_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.param_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam_clause([NotNull] SqlParser.Param_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] SqlParser.ParamContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.method_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod_specifier([NotNull] SqlParser.Method_specifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.table_space_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_space_specifier([NotNull] SqlParser.Table_space_specifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.table_space_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_space_name([NotNull] SqlParser.Table_space_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.table_partitioning_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_partitioning_clauses([NotNull] SqlParser.Table_partitioning_clausesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.range_partitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange_partitions([NotNull] SqlParser.Range_partitionsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.range_value_clause_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange_value_clause_list([NotNull] SqlParser.Range_value_clause_listContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.range_value_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange_value_clause([NotNull] SqlParser.Range_value_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.hash_partitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHash_partitions([NotNull] SqlParser.Hash_partitionsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.individual_hash_partitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndividual_hash_partitions([NotNull] SqlParser.Individual_hash_partitionsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.individual_hash_partition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndividual_hash_partition([NotNull] SqlParser.Individual_hash_partitionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.hash_partitions_by_quantity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHash_partitions_by_quantity([NotNull] SqlParser.Hash_partitions_by_quantityContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.list_partitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_partitions([NotNull] SqlParser.List_partitionsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.list_value_clause_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_value_clause_list([NotNull] SqlParser.List_value_clause_listContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.list_value_partition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_value_partition([NotNull] SqlParser.List_value_partitionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.column_partitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_partitions([NotNull] SqlParser.Column_partitionsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.partition_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartition_name([NotNull] SqlParser.Partition_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.drop_table_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_table_statement([NotNull] SqlParser.Drop_table_statementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] SqlParser.IdentifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.nonreserved_keywords"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonreserved_keywords([NotNull] SqlParser.Nonreserved_keywordsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.unsigned_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnsigned_literal([NotNull] SqlParser.Unsigned_literalContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.general_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneral_literal([NotNull] SqlParser.General_literalContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.datetime_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatetime_literal([NotNull] SqlParser.Datetime_literalContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.time_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTime_literal([NotNull] SqlParser.Time_literalContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.timestamp_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimestamp_literal([NotNull] SqlParser.Timestamp_literalContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.date_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDate_literal([NotNull] SqlParser.Date_literalContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.boolean_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_literal([NotNull] SqlParser.Boolean_literalContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.data_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_type([NotNull] SqlParser.Data_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.predefined_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredefined_type([NotNull] SqlParser.Predefined_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.network_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNetwork_type([NotNull] SqlParser.Network_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.character_string_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacter_string_type([NotNull] SqlParser.Character_string_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.type_length"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_length([NotNull] SqlParser.Type_lengthContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.national_character_string_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNational_character_string_type([NotNull] SqlParser.National_character_string_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.binary_large_object_string_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_large_object_string_type([NotNull] SqlParser.Binary_large_object_string_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.numeric_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric_type([NotNull] SqlParser.Numeric_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.exact_numeric_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExact_numeric_type([NotNull] SqlParser.Exact_numeric_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.approximate_numeric_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitApproximate_numeric_type([NotNull] SqlParser.Approximate_numeric_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.precision_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecision_param([NotNull] SqlParser.Precision_paramContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.boolean_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_type([NotNull] SqlParser.Boolean_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.datetime_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatetime_type([NotNull] SqlParser.Datetime_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.bit_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBit_type([NotNull] SqlParser.Bit_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.binary_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_type([NotNull] SqlParser.Binary_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.value_expression_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_expression_primary([NotNull] SqlParser.Value_expression_primaryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.parenthesized_value_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesized_value_expression([NotNull] SqlParser.Parenthesized_value_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.nonparenthesized_value_expression_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonparenthesized_value_expression_primary([NotNull] SqlParser.Nonparenthesized_value_expression_primaryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.unsigned_value_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnsigned_value_specification([NotNull] SqlParser.Unsigned_value_specificationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.unsigned_numeric_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnsigned_numeric_literal([NotNull] SqlParser.Unsigned_numeric_literalContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.signed_numerical_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSigned_numerical_literal([NotNull] SqlParser.Signed_numerical_literalContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.set_function_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_function_specification([NotNull] SqlParser.Set_function_specificationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.aggregate_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregate_function([NotNull] SqlParser.Aggregate_functionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.general_set_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneral_set_function([NotNull] SqlParser.General_set_functionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.set_function_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_function_type([NotNull] SqlParser.Set_function_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.filter_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilter_clause([NotNull] SqlParser.Filter_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.grouping_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrouping_operation([NotNull] SqlParser.Grouping_operationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.case_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_expression([NotNull] SqlParser.Case_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.case_abbreviation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_abbreviation([NotNull] SqlParser.Case_abbreviationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.case_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_specification([NotNull] SqlParser.Case_specificationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.simple_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_case([NotNull] SqlParser.Simple_caseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.searched_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSearched_case([NotNull] SqlParser.Searched_caseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.simple_when_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_when_clause([NotNull] SqlParser.Simple_when_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.searched_when_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSearched_when_clause([NotNull] SqlParser.Searched_when_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.else_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_clause([NotNull] SqlParser.Else_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.result"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResult([NotNull] SqlParser.ResultContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.cast_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCast_specification([NotNull] SqlParser.Cast_specificationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.cast_operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCast_operand([NotNull] SqlParser.Cast_operandContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.cast_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCast_target([NotNull] SqlParser.Cast_targetContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.value_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_expression([NotNull] SqlParser.Value_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.common_value_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommon_value_expression([NotNull] SqlParser.Common_value_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.numeric_value_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric_value_expression([NotNull] SqlParser.Numeric_value_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] SqlParser.TermContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] SqlParser.FactorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray([NotNull] SqlParser.ArrayContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.numeric_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric_primary([NotNull] SqlParser.Numeric_primaryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.sign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSign([NotNull] SqlParser.SignContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.numeric_value_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric_value_function([NotNull] SqlParser.Numeric_value_functionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.extract_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtract_expression([NotNull] SqlParser.Extract_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.extract_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtract_field([NotNull] SqlParser.Extract_fieldContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.time_zone_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTime_zone_field([NotNull] SqlParser.Time_zone_fieldContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.extract_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtract_source([NotNull] SqlParser.Extract_sourceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.string_value_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_value_expression([NotNull] SqlParser.String_value_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.character_value_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacter_value_expression([NotNull] SqlParser.Character_value_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.character_factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacter_factor([NotNull] SqlParser.Character_factorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.character_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacter_primary([NotNull] SqlParser.Character_primaryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.string_value_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_value_function([NotNull] SqlParser.String_value_functionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.trim_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrim_function([NotNull] SqlParser.Trim_functionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.trim_operands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrim_operands([NotNull] SqlParser.Trim_operandsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.trim_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrim_specification([NotNull] SqlParser.Trim_specificationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.boolean_value_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_value_expression([NotNull] SqlParser.Boolean_value_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.or_predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOr_predicate([NotNull] SqlParser.Or_predicateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.and_predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd_predicate([NotNull] SqlParser.And_predicateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.boolean_factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_factor([NotNull] SqlParser.Boolean_factorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.boolean_test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_test([NotNull] SqlParser.Boolean_testContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.is_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIs_clause([NotNull] SqlParser.Is_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.truth_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTruth_value([NotNull] SqlParser.Truth_valueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.boolean_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_primary([NotNull] SqlParser.Boolean_primaryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.boolean_predicand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean_predicand([NotNull] SqlParser.Boolean_predicandContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.parenthesized_boolean_value_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesized_boolean_value_expression([NotNull] SqlParser.Parenthesized_boolean_value_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.row_value_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRow_value_expression([NotNull] SqlParser.Row_value_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.row_value_special_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRow_value_special_case([NotNull] SqlParser.Row_value_special_caseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.explicit_row_value_constructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicit_row_value_constructor([NotNull] SqlParser.Explicit_row_value_constructorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.row_value_predicand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRow_value_predicand([NotNull] SqlParser.Row_value_predicandContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.row_value_constructor_predicand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRow_value_constructor_predicand([NotNull] SqlParser.Row_value_constructor_predicandContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.table_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_expression([NotNull] SqlParser.Table_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.from_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrom_clause([NotNull] SqlParser.From_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.table_reference_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_reference_list([NotNull] SqlParser.Table_reference_listContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.table_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_reference([NotNull] SqlParser.Table_referenceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.joined_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoined_table([NotNull] SqlParser.Joined_tableContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.joined_table_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoined_table_primary([NotNull] SqlParser.Joined_table_primaryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.cross_join"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCross_join([NotNull] SqlParser.Cross_joinContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.qualified_join"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualified_join([NotNull] SqlParser.Qualified_joinContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.natural_join"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNatural_join([NotNull] SqlParser.Natural_joinContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.union_join"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnion_join([NotNull] SqlParser.Union_joinContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.join_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoin_type([NotNull] SqlParser.Join_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.outer_join_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOuter_join_type([NotNull] SqlParser.Outer_join_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.outer_join_type_part2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOuter_join_type_part2([NotNull] SqlParser.Outer_join_type_part2Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.join_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoin_specification([NotNull] SqlParser.Join_specificationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.join_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoin_condition([NotNull] SqlParser.Join_conditionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.named_columns_join"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamed_columns_join([NotNull] SqlParser.Named_columns_joinContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.table_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_primary([NotNull] SqlParser.Table_primaryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.column_name_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_name_list([NotNull] SqlParser.Column_name_listContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.derived_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDerived_table([NotNull] SqlParser.Derived_tableContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.where_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhere_clause([NotNull] SqlParser.Where_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.search_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSearch_condition([NotNull] SqlParser.Search_conditionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.groupby_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupby_clause([NotNull] SqlParser.Groupby_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.grouping_element_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrouping_element_list([NotNull] SqlParser.Grouping_element_listContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.grouping_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrouping_element([NotNull] SqlParser.Grouping_elementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.ordinary_grouping_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrdinary_grouping_set([NotNull] SqlParser.Ordinary_grouping_setContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.ordinary_grouping_set_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrdinary_grouping_set_list([NotNull] SqlParser.Ordinary_grouping_set_listContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.rollup_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRollup_list([NotNull] SqlParser.Rollup_listContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.cube_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCube_list([NotNull] SqlParser.Cube_listContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.empty_grouping_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmpty_grouping_set([NotNull] SqlParser.Empty_grouping_setContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.having_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHaving_clause([NotNull] SqlParser.Having_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.row_value_predicand_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRow_value_predicand_list([NotNull] SqlParser.Row_value_predicand_listContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.query_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery_expression([NotNull] SqlParser.Query_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.query_expression_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery_expression_body([NotNull] SqlParser.Query_expression_bodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.non_join_query_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNon_join_query_expression([NotNull] SqlParser.Non_join_query_expressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.query_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery_term([NotNull] SqlParser.Query_termContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.non_join_query_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNon_join_query_term([NotNull] SqlParser.Non_join_query_termContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.query_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery_primary([NotNull] SqlParser.Query_primaryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.non_join_query_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNon_join_query_primary([NotNull] SqlParser.Non_join_query_primaryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.simple_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_table([NotNull] SqlParser.Simple_tableContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.explicit_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicit_table([NotNull] SqlParser.Explicit_tableContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.table_or_query_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_or_query_name([NotNull] SqlParser.Table_or_query_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_name([NotNull] SqlParser.Table_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.query_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery_specification([NotNull] SqlParser.Query_specificationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.select_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_list([NotNull] SqlParser.Select_listContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.select_sublist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_sublist([NotNull] SqlParser.Select_sublistContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.derived_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDerived_column([NotNull] SqlParser.Derived_columnContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.qualified_asterisk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualified_asterisk([NotNull] SqlParser.Qualified_asteriskContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.set_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_qualifier([NotNull] SqlParser.Set_qualifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.column_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_reference([NotNull] SqlParser.Column_referenceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.as_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAs_clause([NotNull] SqlParser.As_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.column_reference_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_reference_list([NotNull] SqlParser.Column_reference_listContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.scalar_subquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScalar_subquery([NotNull] SqlParser.Scalar_subqueryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.row_subquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRow_subquery([NotNull] SqlParser.Row_subqueryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.table_subquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_subquery([NotNull] SqlParser.Table_subqueryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.subquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubquery([NotNull] SqlParser.SubqueryContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredicate([NotNull] SqlParser.PredicateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.comparison_predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison_predicate([NotNull] SqlParser.Comparison_predicateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.comp_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComp_op([NotNull] SqlParser.Comp_opContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.between_predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBetween_predicate([NotNull] SqlParser.Between_predicateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.between_predicate_part_2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBetween_predicate_part_2([NotNull] SqlParser.Between_predicate_part_2Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.in_predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIn_predicate([NotNull] SqlParser.In_predicateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.in_predicate_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIn_predicate_value([NotNull] SqlParser.In_predicate_valueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.in_value_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIn_value_list([NotNull] SqlParser.In_value_listContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.pattern_matching_predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPattern_matching_predicate([NotNull] SqlParser.Pattern_matching_predicateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.pattern_matcher"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPattern_matcher([NotNull] SqlParser.Pattern_matcherContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.negativable_matcher"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegativable_matcher([NotNull] SqlParser.Negativable_matcherContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.regex_matcher"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegex_matcher([NotNull] SqlParser.Regex_matcherContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.null_predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNull_predicate([NotNull] SqlParser.Null_predicateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.quantified_comparison_predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantified_comparison_predicate([NotNull] SqlParser.Quantified_comparison_predicateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.quantifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantifier([NotNull] SqlParser.QuantifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.all"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAll([NotNull] SqlParser.AllContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.some"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSome([NotNull] SqlParser.SomeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.exists_predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExists_predicate([NotNull] SqlParser.Exists_predicateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.unique_predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnique_predicate([NotNull] SqlParser.Unique_predicateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.primary_datetime_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_datetime_field([NotNull] SqlParser.Primary_datetime_fieldContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.non_second_primary_datetime_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNon_second_primary_datetime_field([NotNull] SqlParser.Non_second_primary_datetime_fieldContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.extended_datetime_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtended_datetime_field([NotNull] SqlParser.Extended_datetime_fieldContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.routine_invocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoutine_invocation([NotNull] SqlParser.Routine_invocationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.function_names_for_reserved_words"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_names_for_reserved_words([NotNull] SqlParser.Function_names_for_reserved_wordsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_name([NotNull] SqlParser.Function_nameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.sql_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSql_argument_list([NotNull] SqlParser.Sql_argument_listContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.orderby_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderby_clause([NotNull] SqlParser.Orderby_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.sort_specifier_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSort_specifier_list([NotNull] SqlParser.Sort_specifier_listContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.sort_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSort_specifier([NotNull] SqlParser.Sort_specifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.order_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrder_specification([NotNull] SqlParser.Order_specificationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.limit_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLimit_clause([NotNull] SqlParser.Limit_clauseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.null_ordering"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNull_ordering([NotNull] SqlParser.Null_orderingContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="SqlParser.insert_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsert_statement([NotNull] SqlParser.Insert_statementContext context);
}
} // namespace Mlo.Examples.Parsers
